apiVersion: v1
kind: Service
metadata:
  name: proje-bulut-service
spec:
  selector:
    name: proje-bulut-bilisim-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer